-- Datos de ejemplo generados desde object.json
INSERT INTO products (identifier, title, image, image_alt, important, price, details_label, placeholder, category, section_title, poster_image, variant, video_src, cta_label, active, created_at, updated_at)
VALUES
('topper-boy', 'Topper Boy O Girl', '/img/topper_boyOgirl-removebg-preview.png', 'Topper Boy o Girl', 'Fabricado con plástico PLA biodegradable, apto para contacto directo con alimentos.', 4500, 'Detalles / Nombre', 'Ej: Mi Bautismo', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('topper-baby', 'Topper Bebé en Camino', '/img/topper_BBenCamino-removebg-preview.png', 'Topper Baby Shower', 'Diseño exclusivo para Baby Shower. Fabricado en PLA apto para contacto con alimentos.', 4500, 'Detalles / Nombre', 'Ej: Baby Shower - Nombre', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-pastel', 'ADORNOs de PASTEl Baby Girl', '/img/topper_varios-removebg-preview.png', 'Adorno de pastel', 'Base de soporte reforzada ultra-estable.', 2800, 'Nombre y Edad', 'Ej: Bautista - 1 Añito', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('centro-mesa-mamadera', 'Centro de Mesa Mamadera', '/img/mamadera.png', 'Centro de Mesa Mamadera', 'Centro de mesa con forma de mamadera, ideal para Baby Shower.', 3500, 'Nombre o dedicatoria', 'Ej: Sofía', 'centros-mesa', '🏺 Centros de mesa / Accesorios', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('diseño-personalizado', 'Diseñá lo Que Necesites para Tu Evento', '/img/diseno_personalizado.jpeg', 'Diseño Personalizado', 'Creamos adornos, toppers, souvenirs y logos totalmente desde cero.', 0, NULL, NULL, 'diseños-personalizados', '🎨 ¡Dalle vida a tus ideas!', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('cartel-nombre', 'Sr y Sra con Corazón', '/img/letrero_novios.png', 'Cartel de nombre', 'Ideal para la mesa principal. Diseño en dos capas de colores combinables.', 3500, 'Nombre a escribir', 'Ej: Mateo', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('cartel-globo-aerostatico', 'Cartel Globo Aerostático', '/img/cartel_globoAer.png', 'Cartel Globo Aerostático', 'Cartel personalizado con diseño de globo aerostático para Nacimiento.', 3500, 'Nombre a escribir', 'Ej: Mateo', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-boda-mr-mrs', 'Adorno de Pastel Mr & Mrs', '/img/Adorno_boda.png', 'Adorno de pastel Mr & Mrs', 'Adorno de pastel para bodas con estilo elegante y personalizado.', 2800, 'Nombre y mensaje', 'Ej: Mr & Mrs', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-pareja-perro', 'Adorno de Pastel Pareja con su Perro', '/img/adorno_pareja.png', 'Adorno de pastel pareja con su perro', 'Adorno de pastel con diseño romántico y divertido para bodas.', 2800, 'Nombre y mensaje', 'Ej: Nombre de la pareja', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-boda-varios', 'Adorno de Pastel Varios', '/img/adornos_bodas.png', 'Adorno de pastel varios', 'Diseño ideal para combinar con otros elementos de la decoración de boda.', 2800, 'Nombre y mensaje', 'Ej: Nombres de los novios', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('regalo-bodas', 'Regalo de Bodas', '/img/regaloBodas.png', 'Regalo de Bodas', 'Regalo personalizado ideal para recuerdos de boda.', 5000, 'Detalles / Nombre', 'Ej: Nombre y Fecha', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mi-primera-comunion', 'Mi Primera Comunión', '/img/topper_comunion.png', 'Mi Primera Comunión', 'Topper personalizado para celebración de primera comunión.', 4500, 'Nombre y Fecha', 'Ej: Mateo - 2026', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-comunion', 'Adorno Comunión', '/img/adorno_comunion.png', 'Adorno Comunión', 'Letrero o adorno personalizado para primera comunión.', 3500, 'Nombre a escribir', 'Ej: Mateo', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-baby', 'Llavero "Baby Loading"', '/img/llavero_babyS-removebg-preview.png', 'Llavero Baby Loading', 'Excelente acabado 3D, incluye argolla y cadena.', 3999, 'Detalles / Frase', 'Ej: Nombre o fecha del evento', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('letrero-baby', 'Letrero Baby', '/img/letrero_bb.png', 'Letrero Baby', 'Letrero personalizado para Baby Shower con nombre a medida.', 3500, 'Nombre a escribir', 'Ej: Mateo', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-mi-primer-anito', 'Adorno Mi Primer Añito', '/img/adorno1.png', 'Adorno Mi Primer Añito', 'Topper personalizado para celebrar el primer añito.', 4500, 'Nombre y Edad', 'Ej: Mateo - 1 año', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-animalitos-safari', 'Llavero Animalitos Safari', '/img/llaveros_animalesSafari.png', 'Llavero Animalitos Safari', 'Llavero temático safari, ideal como souvenir para primer añito.', 3000, 'Detalles / Nombre', 'Ej: Mateo', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inicial-decorada', 'Inicial Decorada', '/img/cartel.png', 'Inicial Decorada', 'Letrero con inicial decorada, ideal para primer añito.', 3500, 'Inicial y nombre', 'Ej: M', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('cuadro-recuerdo-nacimiento', 'Cuadro Recuerdo Nacimiento', '/img/cuadroRecuerdo.png', 'Cuadro Recuerdo Nacimiento', 'Cuadro recuerdo personalizado ideal para felicitar un nacimiento.', 4500, 'Nombre o mensaje', 'Ej: Bienvenido Mateo', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-espiritu', 'Llavero Espíritu Santo', '/img/llavero_aveComunion-removebg-preview.png', 'Llavero Espíritu Santo', 'Incluye argolla y cadena de metal niquelada.', 3999, 'Detalles / Frase', 'Ej: Mi Comunión - Lucas', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-virgencita', 'Llavero Virgencita', '/img/llavero_bautismoComunion-removebg-preview.png', 'Llavero Virgencita', 'Incluye argolla y cadena de metal niquelada.', 3999, 'Detalles / Frase', 'Ej: Nombre y Fecha', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mi-bautismo', 'Mi Bautismo', '/img/topper_bautismo.png', 'Topper Mi Bautismo', 'Topper personalizado para bautismo, apto para contacto con alimentos.', 4500, 'Nombre y Edad', 'Ej: Mateo - 1 año', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('angel-de-la-guarda', 'Angel de la Guarda', '/img/angel_guarda.png', 'Angel de la Guarda', 'Letrero personalizado con diseño de ángel para bautismo.', 3500, 'Nombre a escribir', 'Ej: Mateo', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-nacimiento', 'Llavero de Pies de Bebé + Corazón', '/img/llavero_nac1.png', 'Llavero pies de bebé', 'Incluye argolla y cadena de metal niquelada.', 3000, 'Detalles / Frase', 'Ej: Nombre y Fecha', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-bebe', 'Llavero Bebé', '/img/llavero_nac2.png', 'Llavero bebé', 'Incluye argolla y cadena de metal niquelada.', 3000, 'Detalles / Frase', 'Ej: Nombre y Fecha', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-cachorro-tejido', 'Llavero de Cachorro Tejido', '/img/llavero_nac3.png', 'Llavero cachorro tejido', 'Incluye argolla y cadena de metal niquelada.', 3000, 'Detalles / Frase', 'Ej: Nombre y Fecha', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('invitacion-interactiva-1', '💌 Invitación Interactiva 1', '/img/invitacion_digitalH.png', 'Invitación interactiva 1', 'Invitación animada con botones interactivos, música, cuenta regresiva y confirmación por WhatsApp.', 0, NULL, NULL, 'invitaciones-digitales', '💌 Invitaciones Digitales Personalizadas', '/img/invitacion_digitalH.png', 'video', '/videos/invitacion_digPrimerA.mp4', 'Ver Demostración', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('invitacion-interactiva-2', '💌 Invitación Interactiva 2', '/img/invitacion_estatica.jpeg', 'Invitación interactiva 2', 'Invitación animada con botones interactivos, música, cuenta regresiva y confirmación por WhatsApp.', 0, NULL, NULL, 'invitaciones-digitales', '💌 Invitaciones Digitales Personalizadas', '/img/invitacion_estatica.jpeg', 'video', '/videos/invitacion_digitalXV.mp4', 'Ver Demostración', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('invitacion-estatica-1', '🖼 Invitación Estática 1', '/img/invitacion_digitalH.png', 'Invitación Estática Premium', 'Diseño elegante en alta calidad para compartir por WhatsApp o Redes Sociales.', 0, NULL, NULL, 'invitaciones-digitales', '💌 Invitaciones Digitales Personalizadas', NULL, 'image', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('invitacion-estatica-2', '💌 Invitación Estática 2', '/img/invitacion_estatica2.jpeg', 'Invitación Estática Personalizada', 'Adaptada completamente al estilo de tu evento.', 0, NULL, NULL, 'invitaciones-digitales', '💌 Invitaciones Digitales Personalizadas', NULL, 'image', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-mis-15', 'Adorno Mis 15', '/img/misXV.png', 'Adorno Mis 15', 'Topper personalizado para mis 15 con gran detalle.', 4500, 'Nombre y Fecha', 'Ej: Sofía - 15 años', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('letrero-mis-15', 'Letrero Mis 15', '/img/letreroxv.png', 'Letrero Mis 15', 'Letrero personalizado para mis 15 con nombre y estilo.', 3500, 'Nombre a escribir', 'Ej: Sofía', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('poni-mis-15', 'Poni', '/img/ponixv.png', 'Poni', 'Souvenir llavero con diseño de poni para mis 15.', 3000, 'Detalles / Nombre', 'Ej: Sofía', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-mis-18', 'Adorno Mis 18', '/img/misxvlll.png', 'Adorno Mis 18', 'Topper personalizado para Mis 18 con diseño elegante.', 4500, 'Nombre y Edad', 'Ej: Sofía - 18 años', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('letrero-mis-18', 'Letrero Mis 18', '/img/letreroxvlll.png', 'Letrero Mis 18', 'Letrero personalizado para Mis 18 con nombre y estilo.', 3500, 'Nombre a escribir', 'Ej: Sofía', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mini-pista-baloncesto', '# Mini Pista de Baloncesto', '/img/xvlll.png', 'Mini Pista de Baloncesto', 'Souvenir deportivo personalizado para Mis 18.', 3000, 'Nombre o dedicatoria', 'Ej: Sofía', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('adorno-mi-graduacion', 'Adorno Mi Graduación', '/img/Captura_de_pantalla_2026-08-04_015037-removebg-preview.png', 'Adorno Mi Graduación', 'Topper personalizado para graduación con diseño elegante.', 4500, 'Nombre y Año', 'Ej: Sofía - Promoción 2026', 'adornos-pastel', '🎂 Adornos para Pastel / Toppers', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('letrero-mi-graduacion', 'Letrero Mi Graduación', '/img/Captura_de_pantalla_2026-08-04_014854-removebg-preview.png', 'Letrero Mi Graduación', 'Letrero personalizado para graduación con nombre y año.', 3500, 'Nombre a escribir', 'Ej: Sofía', 'letreros-nombres', '🏷️ Letreros con nombres personalizados', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('llavero-graduado', 'Llavero Graduado', '/img/llavero_graduacion2-removebg-preview.png', 'Llavero Graduado', 'Llavero souvenir para graduación con detalle de birrete.', 2999, 'Nombre o dedicatoria', 'Ej: Sofía', 'souvenirs-llaveros', '🔑 Souvenirs: Adornos & Llaveros / Soporte exhibidor', NULL, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO product_events (product_id, event) VALUES
(1, 'baby'),
(2, 'baby'),
(3, 'baby'),
(4, 'baby'),
(5, 'personalizados'),
(6, 'casamiento'),
(7, 'nacimiento'),
(8, 'casamiento'),
(9, 'casamiento'),
(10, 'casamiento'),
(11, 'casamiento'),
(12, 'comunion'),
(13, 'comunion'),
(14, 'baby'),
(15, 'baby'),
(16, 'primer'),
(17, 'primer'),
(18, 'primer'),
(19, 'nacimiento'),
(20, 'comunion'),
(21, 'bautismo'),
(21, 'comunion'),
(22, 'bautismo'),
(23, 'bautismo'),
(24, 'nacimiento'),
(25, 'nacimiento'),
(26, 'nacimiento'),
(27, 'invitaciones'),
(28, 'invitaciones'),
(29, 'invitaciones'),
(30, 'invitaciones'),
(31, 'quince'),
(32, 'quince'),
(33, 'quince'),
(34, 'dieciocho'),
(35, 'dieciocho'),
(36, 'dieciocho'),
(37, 'graduacion'),
(38, 'graduacion'),
(39, 'graduacion');

INSERT INTO product_colors (product_id, color) VALUES
(1, 'Dorado'),
(1, 'Plateado'),
(1, 'Blanco'),
(2, 'Dorado'),
(2, 'Plateado'),
(2, 'Amarillo Pastel'),
(3, 'Azul Metalizado'),
(3, 'Plateado Seda'),
(4, 'Blanco'),
(4, 'Rosa Pastel'),
(6, 'Azul (Fondo) y Plateado (Letra)'),
(6, 'Blanco (Fondo) y Celeste (Letra)'),
(6, 'Negro (Fondo) y Plateado (Letra)'),
(6, 'Azul (Fondo) y Blanco (Letra)'),
(7, 'Celeste'),
(7, 'Rosa'),
(7, 'Blanco'),
(8, 'Blanco'),
(8, 'Dorado'),
(8, 'Plateado'),
(9, 'Blanco'),
(9, 'Dorado'),
(9, 'Plateado'),
(10, 'Blanco'),
(10, 'Dorado'),
(10, 'Plateado'),
(11, 'Natural'),
(11, 'Dorado'),
(12, 'Blanco'),
(12, 'Dorado'),
(13, 'Blanco'),
(13, 'Celeste'),
(14, 'Celeste Pastel'),
(14, 'Rosa Pastel'),
(14, 'Amarillo Pastel'),
(15, 'Celeste'),
(15, 'Rosa'),
(15, 'Amarillo Pastel'),
(16, 'Blanco'),
(16, 'Dorado'),
(17, 'Natural'),
(17, 'Amarillo Pastel'),
(18, 'Blanco'),
(18, 'Celeste'),
(19, 'Blanco'),
(19, 'Rosa'),
(19, 'Celeste'),
(20, 'Blanco y Dorado'),
(20, 'Plateado Seda'),
(20, 'Blanco Puro'),
(21, 'Blanco'),
(21, 'Plata'),
(22, 'Blanco'),
(22, 'Dorado'),
(23, 'Blanco'),
(23, 'Celeste'),
(24, 'Blanco'),
(24, 'Rosa Pastel'),
(24, 'Celeste Pastel'),
(25, 'Blanco'),
(25, 'Rosa Pastel'),
(25, 'Celeste Pastel'),
(26, 'Blanco'),
(26, 'Rosa Pastel'),
(26, 'Celeste Pastel'),
(31, 'Blanco'),
(31, 'Dorado'),
(32, 'Blanco'),
(32, 'Rosa'),
(33, 'Rosa'),
(33, 'Lila'),
(34, 'Dorado'),
(34, 'Negro'),
(35, 'Dorado'),
(35, 'Blanco'),
(36, 'Naranja'),
(36, 'Negro'),
(37, 'Negro'),
(37, 'Dorado'),
(38, 'Blanco'),
(38, 'Negro'),
(39, 'Negro'),
(39, 'Plata');
